---
- block:
  - name: Require manual definition of remote-user
    fail:
      msg: |
        When using `--ask-pass` option, use `-u` option to define remote-user:
        ansible-playbook server.yml -e env={{ env }} -u root --ask-pass
    when: cli_ask_pass | default(false)

  - name: Check whether Ansible can connect as root
    local_action: command ansible {{ inventory_hostname }} -m ping -u root {{ cli_options | default('') }}
    failed_when: false
    changed_when: false
    register: root_status
    tags: [connection-tests]

  - name: Set remote user for each host
    set_fact:
      ansible_user: "{{ root_status | default({'failed':false}) | success | ternary('root', admin_user) }}"

  when: ansible_user is not defined

- name: Announce which user was selected
  debug:
    msg: "Note: Ansible will attempt connections as user = {{ ansible_user }}"
