---
sudo: required

env:
  # Test source install on latest supported OSes.
  - distro: centos7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    playbook: test-source.yml
    GIT_VERSION: 2.9.3
  - distro: ubuntu1604
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    playbook: test-source.yml
    GIT_VERSION: 2.9.3

  # Test package install on all supported OSes.
  - distro: centos7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    playbook: test.yml
    GIT_VERSION: 1.8.3.1
  - distro: centos6
    init: /sbin/init
    run_opts: "--privileged"
    playbook: test.yml
    GIT_VERSION: 1.7.1
  - distro: ubuntu1604
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    playbook: test.yml
    GIT_VERSION: 2.7.4
  - distro: ubuntu1404
    init: /sbin/init
    run_opts: "--privileged"
    playbook: test.yml
    GIT_VERSION: 1.9.1
  - distro: ubuntu1204
    init: /sbin/init
    run_opts: "--privileged"
    playbook: test.yml
    GIT_VERSION: 1.7.9.5
  - distro: debian8
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    playbook: test.yml
    GIT_VERSION: 2.1.4

services:
  - docker

before_install:
  # Pull container.
  - 'sudo docker pull geerlingguy/docker-${distro}-ansible:latest'

script:
  - container_id=$(mktemp)
  # Run container in detached state.
  - 'sudo docker run --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} geerlingguy/docker-${distro}-ansible:latest "${init}" > "${container_id}"'

  # Ansible syntax check.
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/${playbook} --syntax-check'

  # Test role.
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/${playbook}'

  # Test role idempotence.
  - idempotence=$(mktemp)
  - sudo docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/${playbook} | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Ensure Git is installed and at the right version.
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm which git'
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm test -x /usr/bin/git'

  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm git --version'
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm /usr/bin/git --version | grep -qF "$GIT_VERSION"'

  # Clean up.
  - 'sudo docker stop "$(cat ${container_id})"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
