---
port: 80
ansible_os_family: "Debian"
ansible_distribution: "Ubuntu"
ansible_distribution_release: "precise"
nginx_worker_processes: 4
ansible_pkg_mgr: apt
ansible_distribution_version: 16.10
www_root: /srv/www
